### PR TITLE
Add ability to filter the whole batch of icons.

### PR DESCRIPTION
**Pull request by trading-peter**
Searching though the icons with the browser itself is frustrating because the list doesn't scroll, so I implemented a filter. Maybe you find it useful? It's somewhat limited and doesn't show a "Sorry, no matches." screen jet.

Here's a preview:
polyicon_filter

### CODE REVIEW

**Comment by ebidel** [comment]
Hmm. The list and code view scroll for me. How do I repo?

**Comment by trading-peter** [comment]
Sorry, I wasn't very precise with my explanation.
The browser of course scrolls the list, but as the icon list is partly hidden by the bottom panel it won't scroll them into view. The scroll offset is high enough but the bottom panels lay above the part of the list.

One example: Search for `spa` and go through results:
screencast 2016-03-14 16-56-05

Also IMHO, I also find searching with the browser cumbersome because it's needs so much eye moment to find the marked icons.

**Comment by ebidel** [comment]
Ah I see what you mean! The filtering is nice, but can we do it in vanilla js. I'm not sure we need the dependency for string matching :)

**Comment by trading-peter** [comment]
Yep, can do that if you prefer. I will update the pr shortly.

**Comment by trading-peter** [comment]
I'm unsure how to include the license of the 3th party project. I would greatly appreciate if you could explain to me how to do this? Or is it correct this way?

**Comment by ebidel** [comment]
I'd prefer if we remove the 3rd party dep altogether and just use vanilla js to do the filtering.

**Comment by trading-peter** [comment]
You mean even remove the `fuzzysearch` function I striped out of the 3th party project? The whole thing is literally only 20 lines of code. The function is now inside `index.html` and no additional externals scripts are loaded :)

**Comment by ebidel** [comment]
Ah cool. Didn't notice that. I'll give this a look in a bit.

**Comment by trading-peter** [comment]
Hmm... I removed the 3th party code already... You'll have to go one commit
back. Sorry

Von meinem Smartphone gesendet
Am 14.03.2016 10:25 nachm. schrieb "Eric Bidelman" <notifications@github.com

**Comment by ebidel** [comment]
LGTM

**Pull request merged**
